-- This script cleans the database environment
-- Dropping child tables first, then parent tables
DROP TABLE PAYMENTS CASCADE CONSTRAINTS;
DROP TABLE LEASES CASCADE CONSTRAINTS;
DROP TABLE PROPERTIES CASCADE CONSTRAINTS;
DROP TABLE TENANTS CASCADE CONSTRAINTS;
DROP TABLE OWNERS CASCADE CONSTRAINTS;
