-- OWNERS: Stores primary property owners
CREATE TABLE OWNERS (
    OwnerID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FullName VARCHAR2(100) NOT NULL,
    Email VARCHAR2(100) UNIQUE,
    Phone VARCHAR2(20)
);

-- TENANTS: Stores individuals renting units
CREATE TABLE TENANTS (
    TenantID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FullName VARCHAR2(100) NOT NULL,
    Email VARCHAR2(100) UNIQUE,
    Phone VARCHAR2(20)
);

-- PROPERTIES: Stores unit details linked to owners
CREATE TABLE PROPERTIES (
    PropertyID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OwnerID INT NOT NULL,
    Address VARCHAR2(255) NOT NULL,
    PropertyType VARCHAR2(50),
    RentAmount NUMBER(10, 2),
    CONSTRAINT fk_prop_owner FOREIGN KEY (OwnerID) REFERENCES OWNERS(OwnerID)
);

-- LEASES: Links a property to a tenant for a specific time
CREATE TABLE LEASES (
    LeaseID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PropertyID INT NOT NULL,
    TenantID INT NOT NULL,
    StartDate DATE NOT NULL,
    EndDate DATE,
    MonthlyRent NUMBER(10, 2),
    DepositAmount NUMBER(10, 2),
    CONSTRAINT fk_lease_prop FOREIGN KEY (PropertyID) REFERENCES PROPERTIES(PropertyID),
    CONSTRAINT fk_lease_tenant FOREIGN KEY (TenantID) REFERENCES TENANTS(TenantID)
);

-- PAYMENTS: Tracks rent collection history
CREATE TABLE PAYMENTS (
    PaymentID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    LeaseID INT NOT NULL,
    PaymentDate DATE DEFAULT SYSDATE,
    AmountPaid NUMBER(10, 2),
    PaymentStatus VARCHAR2(20) CHECK (PaymentStatus IN ('Paid', 'Pending', 'Overdue')),
    PaymentMethod VARCHAR2(50),
    CONSTRAINT fk_pay_lease FOREIGN KEY (LeaseID) REFERENCES LEASES(LeaseID)
);
